mysql:
  username: root
  password: Mysql123456/
  host: 112.74.86.176
  port: 3306
kafka:
  host: localhost
  port: 9092
redis:
  host: localhost
  port: 6379
  password: redis9898008
elasticsearch:
  host: 112.74.86.176
  port: 9200
